sudo: false
cache:
  yarn: true
  directories:
  - node_modules
language: node_js
node_js: lts/*
env:
  global:
    secure: c6M9muLqt46u4rzczm+IW+IThPBdOkHIU9yXOZvI86bk3LaeX9A6psIrbZ3rmaUJZl4pPTzhfZcxonwbS3td69vR79q/JoizHK+TdyDHUFyBDsJfgOwUUEMMnwHzjgg3ZWTsZe4GKdtj6hFdlOKgeZqfUPzLauq0vmSfkao2NUErzkGaN3w3z4C6jTwbdVFSxVW21Cw+GgFPCA14D2Z6s/c+ZJWcWHFRiYKkTUNQhy+iiN1KTlHlw/txYtUX2E7lvsB9Q9zdES6SqdulqsLlf/N5vRsdnYosijEA3YjHpv6bLVnkagBYeHPLj1L8R5QJAqobTcxqfL3CotP3h+kUlrGZGtwDfXnSP2ndZyVd0DFQRG+WZa1tWND3Srgz8XVqQq8BkfcruObwovF1exlf6mGmMFii/pxSLvC2k/4hGJYhJLiHb4y7onLnbe9K1d1KTkoKxlreauwWTEgbZ+lR0vXs2rKJUUdatObihc/09UB5Uze1OYbWKJciigiPiPY9gzJqkbJdKy0n8b8BWPAvBexJGQPeU8g3PMBuGeSr1Ga23JGNENgYfYKyr1FRc4uUL+oAByMwOQ9kkoDQMaz7vywBtVzuWBGgVGAP24xGfQlqalm0sPzPGprME6TADJLfvzxdUjzkXd75VLq2ov3cRzbmuLD7b80n0poCeqRVwCM=
stages:
- test
- name: deploy
jobs:
  include:
  - stage: Test
    name: lint
    script:
    - yarn lint
  - script:
    - yarn test
    name: test
  - script:
    - yarn build-storybook
    name: build storybook
  - stage: deploy
    name: deploy to gh-page
    env: gh-page
    script:
    - yarn build
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      local-dir: public
      on:
        branch: master
